# Programming for Data Analysis
# Assignment 2020

## ***Purpose of numpy.random Package***
<p align="justify"> Numpy is a data maniputaltion library for the python programming language, the tools of numpy operate on arrays of numbers. numpy.random is used for the generation of random numbers and integers and is important for data science, statistics and machine learning. When ever you want to generate an array of random numbers you need to use numpy.random. The numpy.random package has multiple functions to generate the random n-dimensional array for various distributions. This package help to clean up your data and organise it into an efficeint work flow.</p>

## ***Use of Simple Random Data Function***

There are tex simple random data function which can be seen from the image below.
![SimpleRandomData.jpg](attachment:SimpleRandomData.jpg)
These are simple functions that will return random numbers or integers when given a defined attribute such as size or shape.  I will look at the integer function, choice function and bytes function  in the simple category.

The random integers function returns random integers from low (inclusive) to high (exclusive) 


In [1]:
import numpy as np
rng = np.random.default_rng()
rng.integers(2, size =10)

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [2]:
rng.integers(5, size=(2,4))

array([[1, 4, 3, 4],
       [0, 1, 4, 3]], dtype=int64)

Below is the bytes function this gives random bytes when the length is requested.  You can see what is returned for when the lengty is set to 20 and 100 below.

In [3]:
np.random.default_rng(0).bytes(20)

b'_\x82\xc2\xd9\xcf\xeb\x0f\xa3!\xd7\xd9\x82\xf8\xbd\x10E\xb8\xe8\xcdN'

In [4]:
np.random.default_rng(0).bytes(100)

b"_\x82\xc2\xd9\xcf\xeb\x0f\xa3!\xd7\xd9\x82\xf8\xbd\x10E\xb8\xe8\xcdN\xa9=}\n\x1d\xf0B\x13\xb6';\x04;Q\xde,xz2\xd0N\x1c@\xa6yY\xaa\xe9\x7f\xb2\xed\x80q{L\x9bE\x9a\x82\xf8_I\xc0\xba\xbf\x7f\xdc\xa1\xe7\x01+\x8b\xed\xbfV\x8f\x07\xe8`\xefL7\x00GM\xc7\xdb\xd0\xb0\x90\xbe\xabhx\xb3\x00\xf0\xf5\xe6d"

## ***Use of Permutations Functions***

There are Two permutation functions in the numpy.random package.
[shuffle(x)](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle)
Modify a sequence in-place by shuffling its contents.

[permutation(x)](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation) randomly permutate a sequence, or return a permuted range. 

Shuffle(x) this will give you random integers given the defined x (50 below) in a random order as shown in the below code.  This function will change the order of the array but the contents will remain the same each time it is run. 

In [5]:
import numpy as np
rng = np.random.default_rng()
arr = np.arange(50)
rng.shuffle (arr)
arr

array([ 9, 36, 13, 46,  1, 42,  6, 26, 41, 18, 47, 23, 21, 38,  8, 11,  0,
       32, 31,  4, 33, 39, 22, 48,  3, 15,  2, 27, 40,  7, 19, 17, 35,  5,
       24, 25, 44, 49, 37, 29, 34, 43, 10, 28, 16, 45, 20, 30, 12, 14])

In this example I have asked for 15 random integres reshaped to 3 rows of 5.

In [6]:
arr = np.arange(15).reshape((3,5))
rng.shuffle(arr)
arr

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

Permutation(x) randomly returns a sequence in the first example X is ten and it returns an array of 1 to 10 integers in a random order.  In the second example x is 100 and I have reshaped the structure of the array rather than a singel string it is arranced as five rows with 20 integers in each row. 

In [7]:
arr=np.random.default_rng()
rng.permutation(10)

array([0, 9, 4, 8, 2, 7, 3, 5, 6, 1])

In [8]:
arr=np.arange(100).reshape((5,20))
rng.permutation(arr)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

## ***Use and Purpose of Distribution Functions***
In total there are 36 distribution functionsin the numpy.random package. ![Distribusitons.png](attachemnt:Distributions.png) I will explain the used an purpose of the followign five Distribution functions.
1. **lognormal**
2. **multinomial**
3. **multivariate_normal**
4. **noncentral_f**
5. **uniform**